import type { NextPage } from 'next'
import Head from 'next/head';
import { Badge, Stack, Skeleton } from '@chakra-ui/react'
import Link from 'next/link';

import Header from '../component/header';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
   return (
      <div className={styles.container}>
         <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
         </Head>

         <main className="container">
            <Header

            />
            <div className="container p-4">
               <h1 className="font-bold text-2xl mb-3">Pokédex (892)</h1>
               <div className="grid grid-cols-2 gap-2">
                  <Link href="/">
                     <a>
                        <Skeleton className="rounded-md">
                           <div className="bg-emerald-400 rounded-md text-white p-2">
                              <div className>
                                 <img src={'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/1.png'} />
                              </div>
                              <div className="">
                                 <span>#001</span>
                                 <h3>Bulbarus</h3>
                                 <div className="">
                                    <Stack direction='row'>
                                       <Badge className="rounded-full" colorScheme='green'>Success</Badge>
                                       <Badge className="rounded-full" colorScheme='red'>Removed</Badge>
                                       <Badge className="rounded-full" colorScheme='purple'>New</Badge>
                                    </Stack>
                                 </div>
                              </div>
                           </div>
                        </Skeleton>
                     </a>
                  </Link>
                  <div className="bg-emerald-400 rounded-md text-white p-2">
                     <div className>
                        <img src={'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/1.png'} />
                     </div>
                     <div className="">
                        <span>#001</span>
                        <h3>Bulbarus</h3>
                        <div className="">
                           <Stack direction='row'>
                              <Badge className="rounded-full" colorScheme='green'>Success</Badge>
                              <Badge className="rounded-full" colorScheme='red'>Removed</Badge>
                              <Badge className="rounded-full" colorScheme='purple'>New</Badge>
                           </Stack>
                        </div>
                     </div>
                  </div>
                  <div className="bg-emerald-400 rounded-md text-white p-2">
                     <div className>
                        <img src={'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/1.png'} />
                     </div>
                     <div className="">
                        <span>#001</span>
                        <h3>Bulbarus</h3>
                        <div className="">
                           <Stack direction='row'>
                              <Badge className="rounded-full" colorScheme='green'>Success</Badge>
                              <Badge className="rounded-full" colorScheme='red'>Removed</Badge>
                              <Badge className="rounded-full" colorScheme='purple'>New</Badge>
                           </Stack>
                        </div>
                     </div>
                  </div>
                  <div className="bg-emerald-400 rounded-md text-white p-2">
                     <div>
                        <img src={'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/1.png'} />
                     </div>
                     <div className="">
                        <span>#001</span>
                        <h3>Bulbarus</h3>
                        <div className="">
                           <Stack direction='row'>
                              <Badge className="rounded-full" colorScheme='green'>Success</Badge>
                              <Badge className="rounded-full" colorScheme='red'>Removed</Badge>
                              <Badge className="rounded-full" colorScheme='purple'>New</Badge>
                           </Stack>
                        </div>
                     </div>
                  </div>
               </div>
            </div>
         </main>
      </div>
   )
}

export default Home
